[tool.setuptools]
packages = ["criu_api"]

[project]
name = "criu_api"
version = "0.3.2"
description = "Python API for CRIU"
authors = [
    {name = "Andrii Herheliuk"}
]
dependencies = ["psutil"]
license = { text = "MIT" }
